name: python-flask
environment: dev
replicaCount: 1
image:
  repository: Adybaeva/dev-code
  tag: c07b370
  pullPolicy: Always
service:
  name: python-flask-svc
  type: ClusterIP
  port: 80
  targetPort: 5000
resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi
